const gs1Sources = {
  steps: 'https://www.gs1.org/standards/barcodes/10-steps-to-barcode-your-product/english',
  get: 'https://www.gs1.org/standards/get-barcodes',
  quality: 'https://support.gs1.org/support/solutions/articles/43000734141-what-should-i-check-to-ensure-good-quality-barcodes-',
  verify: 'https://www.gs1.org/services/verified-by-gs1',
};

export const ADDITIONAL_GUIDE_PAGES = [
  {
    en: {
      route: 'guides/ean-13-food-products',
      title: 'EAN-13 for Food Products: Setup and Printing Guide',
      description: 'Prepare an EAN-13 barcode for a food product: obtain the correct GTIN, separate product variants, verify the check digit and test the printed label.',
      h1: 'How to prepare an EAN-13 barcode for a food product',
      lead: 'A barcode image is the final step, not the product number itself. Start with the correct GTIN for the exact product variant, then generate, place, print and scan-test the EAN-13 symbol before packaging goes into production.',
      datePublished: '2026-07-22',
      cta: ['Open the EAN-13 generator', '/ean-13/'],
      labels: { kicker: 'Food product barcode guide', comparison: 'From product decision to printed label', choose: 'Choose the correct identification level', examples: 'Example identifiers and labels', mistakes: 'Mistakes that cause retail problems', faq: 'Frequently asked questions', sources: 'Official GS1 references', related: 'Related tools and guides' },
      table: [
        ['Stage', 'What to decide', 'Expected result', 'Useful tool'],
        ['Identify', 'Exact product, brand, quantity and packaging level', 'One authorised GTIN for that trade item', 'Your GS1 Member Organisation'],
        ['Validate', 'Length, leading zeroes and calculated final check digit', 'A structurally valid GTIN-13', 'GS1 calculator or this validator'],
        ['Create', 'EAN-13 size, colour, quiet zones and readable digits', 'Print-ready barcode artwork', 'EAN-13 generator'],
        ['Verify', 'Actual package, material, printer and production process', 'A label that scans in its intended environment', 'Scanner test and barcode verifier'],
      ],
      choices: [
        ['Consumer unit sold at checkout', 'Use the GTIN assigned to that exact trade item and encode a GTIN-13 as EAN-13. Keep all 13 human-readable digits below the symbol and confirm retailer requirements before printing.'],
        ['Different flavour, weight or pack count', 'Treat a commercially different variant as a separate trade item. Do not reuse the same retail identifier merely because the brand or package design is similar.'],
        ['Case or outer packaging', 'A case can require a different GTIN and a logistics carrier such as ITF-14 or GS1-128. Do not automatically copy the consumer-unit EAN-13 onto every packaging level.'],
        ['Expiry date or batch number required', 'EAN-13 carries the product identifier only. Use GS1-128 or GS1 DataMatrix when the process also needs batch, expiry or serial data.'],
      ],
      examples: [
        ['Valid GTIN-13', '5901234123457', 'The final 7 is calculated from the preceding twelve digits. The generator rejects a complete identifier with a mismatched check digit.'],
        ['Twelve digits supplied', '590123412345', 'The tool can append a calculated check digit, but it cannot confirm that the number was licensed to your company.'],
        ['Batch and expiry', '(01)05901234123457 (17)270630 (10)LOT42', 'This is Application Identifier data for a GS1 carrier, not content for a plain EAN-13 symbol.'],
      ],
      mistakes: [
        'Inventing a 13-digit retail number in a graphics tool. A correct check digit proves the structure, not ownership or global uniqueness. Obtain the GTIN through GS1.',
        'Using one GTIN for products that differ in a way relevant to ordering, pricing or supply-chain handling, such as weight, recipe or pack count.',
        'Cropping the quiet zones, placing artwork too close to the bars or using unsuitable bar and background colours.',
        'Testing only a PNG on a monitor. Print scale, material, package curvature and finishing can change scan quality.',
      ],
      faq: [
        ['Can I make up an EAN-13 number for a food product?', 'Not for a product that needs a globally unique GS1 identifier. This tool renders and validates structure; it does not assign GTINs. Obtain the identifier through GS1.'],
        ['Does every flavour or package size need a different barcode?', 'When variants are separate trade items for ordering or sale, they normally require distinct GTINs. Apply current GS1 GTIN Management rules to the exact change.'],
        ['Can EAN-13 include a batch number or expiry date?', 'No. EAN-13 represents the GTIN. Batch, expiry and serial data use GS1 Application Identifiers in a suitable carrier such as GS1-128 or GS1 DataMatrix.'],
        ['Is scanning with a phone enough to approve packaging?', 'A phone scan is a useful basic check but does not replace formal verification of dimensions and print quality when a retailer or production process requires it.'],
      ],
      links: [['EAN-13 generator', '/ean-13/'], ['GS1 generator', '/gs1-barcode-generator'], ['GTIN, EAN and UPC guide', '/guides/gtin-ean-upc'], ['Print labels from CSV', '/bulk-barcode-generator'], ['Free generator in a business', '/guides/free-barcode-generator-business-use']],
      sources: [['GS1: 10 steps to barcode a product', gs1Sources.steps], ['GS1: get a barcode and GTIN', gs1Sources.get], ['GS1: barcode quality checks', gs1Sources.quality]],
    },
    pl: {
      route: 'poradniki/kod-ean-13-produkt-spozywczy',
      title: 'Kod EAN-13 dla produktu spożywczego - poradnik',
      description: 'Przygotuj EAN-13 dla produktu spożywczego: uzyskaj właściwy GTIN, rozdziel warianty, sprawdź cyfrę kontrolną i przetestuj gotową etykietę.',
      h1: 'Jak przygotować kod EAN-13 dla produktu spożywczego',
      lead: 'Obraz kodu kreskowego jest ostatnim etapem, a nie numerem produktu. Zacznij od właściwego GTIN dla konkretnego wariantu, a następnie wygeneruj, umieść, wydrukuj i sprawdź symbol EAN-13 przed produkcją opakowań.',
      datePublished: '2026-07-22',
      cta: ['Otwórz generator EAN-13', '/pl/ean-13/'],
      labels: { kicker: 'Poradnik kodu dla żywności', comparison: 'Od decyzji o produkcie do gotowej etykiety', choose: 'Wybierz właściwy poziom identyfikacji', examples: 'Przykładowe identyfikatory i etykiety', mistakes: 'Błędy powodujące problemy w sprzedaży', faq: 'Najczęstsze pytania', sources: 'Oficjalne źródła GS1', related: 'Powiązane narzędzia i poradniki' },
      table: [
        ['Etap', 'Co trzeba ustalić', 'Oczekiwany wynik', 'Przydatne narzędzie'],
        ['Identyfikacja', 'Dokładny produkt, marka, ilość i poziom opakowania', 'Jeden uprawniony GTIN dla tej jednostki', 'Lokalna organizacja GS1'],
        ['Walidacja', 'Długość, zera wiodące i ostatnia cyfra', 'Poprawny strukturalnie GTIN-13', 'Kalkulator GS1 lub ten walidator'],
        ['Generowanie', 'Rozmiar, kolory, jasne marginesy i cyfry pod kodem', 'Grafika gotowa do druku', 'Generator EAN-13'],
        ['Weryfikacja', 'Opakowanie, materiał, drukarka i proces produkcji', 'Etykieta czytelna w docelowym środowisku', 'Test skanerem i weryfikator'],
      ],
      choices: [
        ['Jednostka sprzedawana przy kasie', 'Użyj GTIN przypisanego do dokładnie tej jednostki i zapisz GTIN-13 jako EAN-13. Zachowaj 13 cyfr pod kodem i potwierdź wymagania odbiorcy przed drukiem.'],
        ['Inny smak, masa lub liczba sztuk', 'Wariant różniący się handlowo traktuj jako osobną jednostkę. Nie używaj tego samego identyfikatora tylko dlatego, że marka lub projekt opakowania są podobne.'],
        ['Karton lub opakowanie zbiorcze', 'Karton może wymagać osobnego GTIN i nośnika logistycznego, np. ITF-14 albo GS1-128. Nie kopiuj automatycznie kodu jednostki konsumenckiej.'],
        ['Wymagana partia lub data ważności', 'EAN-13 przenosi wyłącznie identyfikator produktu. Dla partii, daty lub numeru seryjnego użyj np. GS1-128 albo GS1 DataMatrix.'],
      ],
      examples: [
        ['Poprawny GTIN-13', '5901234123457', 'Ostatnia cyfra 7 jest obliczona z wcześniejszych dwunastu. Generator odrzuci pełny numer z błędną cyfrą kontrolną.'],
        ['Podane dwanaście cyfr', '590123412345', 'Generator może dodać obliczoną cyfrę, ale nie potwierdzi, że numer został przydzielony Twojej firmie.'],
        ['Partia i data ważności', '(01)05901234123457 (17)270630 (10)PARTIA42', 'To dane z Identyfikatorami Zastosowania dla nośnika GS1, nie zawartość zwykłego EAN-13.'],
      ],
      mistakes: [
        'Wymyślanie trzynastocyfrowego numeru detalicznego. Poprawna cyfra kontrolna potwierdza strukturę, ale nie własność ani globalną unikalność. GTIN uzyskaj przez GS1.',
        'Używanie jednego GTIN dla produktów różniących się masą, recepturą, liczbą sztuk albo inną cechą istotną dla zamówień i sprzedaży.',
        'Przycinanie jasnych pól ochronnych, umieszczanie grafiki zbyt blisko kresek lub używanie niewłaściwych kolorów.',
        'Testowanie wyłącznie PNG na monitorze. Skala, materiał, krzywizna opakowania i wykończenie mogą zmienić jakość odczytu.',
      ],
      faq: [
        ['Czy mogę sam wymyślić numer EAN-13 dla produktu spożywczego?', 'Nie dla produktu wymagającego globalnie unikalnego identyfikatora GS1. Narzędzie renderuje i sprawdza strukturę, ale nie przydziela GTIN.'],
        ['Czy każdy smak albo rozmiar opakowania potrzebuje innego kodu?', 'Jeśli warianty są osobnymi jednostkami w zamówieniach lub sprzedaży, zwykle potrzebują oddzielnych GTIN. Zastosuj aktualne reguły zarządzania GTIN.'],
        ['Czy EAN-13 może zawierać numer partii albo datę ważności?', 'Nie. EAN-13 przedstawia GTIN. Partia, data i numer seryjny korzystają z Identyfikatorów Zastosowania w nośniku GS1-128 lub GS1 DataMatrix.'],
        ['Czy odczyt telefonem wystarczy do zatwierdzenia opakowania?', 'Skan telefonem jest testem podstawowym, ale nie zastępuje formalnej weryfikacji wymiarów i jakości druku, gdy wymaga jej odbiorca lub produkcja.'],
      ],
      links: [['Generator EAN-13', '/pl/ean-13/'], ['Generator GS1', '/pl/generator-kodow-gs1'], ['Poradnik GTIN, EAN i UPC', '/pl/poradniki/gtin-ean-upc'], ['Druk etykiet z CSV', '/pl/generator-kodow-z-csv'], ['Darmowy generator w firmie', '/pl/poradniki/darmowy-generator-kodow-dla-firmy']],
      sources: [['GS1: 10 kroków do oznaczenia produktu', gs1Sources.steps], ['GS1: uzyskanie kodu i GTIN', gs1Sources.get], ['GS1: kontrola jakości kodu', gs1Sources.quality]],
    },
  },
  {
    en: {
      route: 'guides/free-barcode-generator-business-use',
      title: 'Can a Free Barcode Generator Be Used for Business?',
      description: 'Learn when a free barcode generator is suitable for company use, what it does not provide, and how to validate identifiers, files and printed labels.',
      h1: 'Can you use a free barcode generator in a business?',
      lead: 'Yes, this generator can create barcode artwork for commercial workflows without a fee. The key distinction is between generating the symbol and obtaining the right to use the identifier encoded inside it.',
      datePublished: '2026-07-22',
      cta: ['Create a barcode now', '/'],
      labels: { kicker: 'Business use guide', comparison: 'What the free tool provides', choose: 'Match the identifier to the workflow', examples: 'Practical business scenarios', mistakes: 'Limits you must account for', faq: 'Frequently asked questions', sources: 'Rules and official references', related: 'Related tools and guides' },
      table: [
        ['Need', 'Provided here', 'Still your responsibility', 'Recommended check'],
        ['Create artwork', 'PNG, SVG, PDF and ZIP exports', 'Correct data, dimensions and placement', 'Scan the file and physical sample'],
        ['Retail identifier', 'Check digit validation and EAN/UPC rendering', 'A legitimately assigned unique GTIN', 'Verify with GS1 and your retailer'],
        ['Internal operations', 'Code 128, Code 39, QR and 2D formats', 'An allocation rule without duplicates', 'Test scanners and software paths'],
        ['Production printing', 'A4, Letter and thermal layouts', 'Calibration, media and final print quality', 'Print at 100% and inspect the label'],
      ],
      choices: [
        ['Retail products', 'Use an authorised GTIN and the carrier accepted by the retailer or marketplace. The generator can encode the value but cannot grant or register it.'],
        ['Internal stock and locations', 'Code 128 is often practical for company-controlled SKU, bin and asset identifiers. Keep one source of truth so values are never reused.'],
        ['Customer-facing QR codes', 'Use a durable HTTPS destination you control, preserve contrast and quiet space, and test the print at the expected distance.'],
        ['Regulated or contractual labels', 'Follow the applicable industry, customer and legal specification. A graphics tool does not replace formal verification, certification or approval.'],
      ],
      examples: [
        ['Internal shelf code', 'WH-A-04-017', 'Code 128 can encode this location when your warehouse system controls the allocation rule.'],
        ['Retail EAN-13', '5901234123457', 'The tool validates and renders; GS1 records and trading-partner rules determine whether the GTIN is yours.'],
        ['Batch label job', 'products.csv → PDF', 'The bulk tool reports invalid rows and creates a print layout locally without uploading the product list.'],
      ],
      mistakes: [
        'Assuming that a generated image includes ownership of the number. The symbol and identifier are separate concerns.',
        'Skipping duplicate prevention for internal codes. A valid Code 128 value can still point to the wrong item when reused.',
        'Publishing labels without checking scale, quiet zones, contrast, printer calibration and the final material.',
        'Treating a successful phone scan as proof of compliance with a retailer, GS1 application specification or verification requirement.',
      ],
      faq: [
        ['May I use exported PNG, SVG and PDF files commercially?', 'Yes. The tool does not charge for generating barcode artwork. You remain responsible for the data, identifier rights, third-party requirements and final print.'],
        ['Does a free EAN-13 generator give me a product number?', 'No. It can calculate a check digit and render EAN-13, but globally unique retail GTINs are issued through GS1 Member Organisations.'],
        ['Do I need an account?', 'No for individual generation, decoding and limited bulk exports. An account adds saved codes, templates, printer profiles and print-job history.'],
        ['Are product values uploaded during a batch export?', 'CSV parsing and barcode generation run in the browser. Account features send only records you explicitly save to the configured Supabase project.'],
      ],
      links: [['Single barcode generator', '/'], ['Bulk CSV generator', '/bulk-barcode-generator'], ['Barcode decoder', '/decoder'], ['GTIN, EAN and UPC guide', '/guides/gtin-ean-upc'], ['EAN-13 for food products', '/guides/ean-13-food-products']],
      sources: [['GS1: get a barcode and GTIN', gs1Sources.get], ['GS1: verify a GTIN', gs1Sources.verify], ['Barcode Generator terms', 'https://barcode-generator.daytodayapps.com/terms']],
    },
    pl: {
      route: 'poradniki/darmowy-generator-kodow-dla-firmy',
      title: 'Czy darmowy generator kodów można używać w firmie?',
      description: 'Sprawdź, kiedy darmowy generator kodów nadaje się do firmy, czego nie zapewnia i jak zweryfikować identyfikator, plik oraz wydrukowaną etykietę.',
      h1: 'Czy można używać darmowego generatora kodów w firmie?',
      lead: 'Tak, ten generator pozwala bezpłatnie tworzyć grafiki kodów do zastosowań komercyjnych. Trzeba jednak odróżnić wygenerowanie symbolu od uzyskania prawa do identyfikatora zapisanego w jego wnętrzu.',
      datePublished: '2026-07-22',
      cta: ['Utwórz kod teraz', '/pl/'],
      labels: { kicker: 'Poradnik dla firm', comparison: 'Co zapewnia bezpłatne narzędzie', choose: 'Dopasuj identyfikator do procesu', examples: 'Praktyczne scenariusze firmowe', mistakes: 'Ograniczenia, które trzeba uwzględnić', faq: 'Najczęstsze pytania', sources: 'Zasady i oficjalne źródła', related: 'Powiązane narzędzia i poradniki' },
      table: [
        ['Potrzeba', 'Co zapewnia strona', 'Za co odpowiada firma', 'Zalecana kontrola'],
        ['Utworzenie grafiki', 'Eksport PNG, SVG, PDF i ZIP', 'Poprawne dane, wymiary i umieszczenie', 'Odczytaj plik i fizyczną próbkę'],
        ['Identyfikator detaliczny', 'Walidacja cyfry i renderowanie EAN/UPC', 'Legalnie przydzielony unikalny GTIN', 'Sprawdź GS1 i wymagania sprzedawcy'],
        ['Proces wewnętrzny', 'Code 128, Code 39, QR i formaty 2D', 'Numeracja bez duplikatów', 'Przetestuj skanery i systemy'],
        ['Druk produkcyjny', 'Układy A4, Letter i termiczne', 'Kalibracja, materiał i jakość końcowa', 'Drukuj w skali 100% i sprawdź'],
      ],
      choices: [
        ['Produkty detaliczne', 'Użyj uprawnionego GTIN i nośnika akceptowanego przez sprzedawcę. Generator może zakodować wartość, ale jej nie nadaje ani nie rejestruje.'],
        ['Wewnętrzny magazyn i lokalizacje', 'Code 128 często sprawdza się dla wewnętrznych SKU, miejsc i zasobów. Ustal jedno źródło numeracji, aby wartości nie były używane ponownie.'],
        ['Kody QR dla klientów', 'Użyj trwałego adresu HTTPS pod własną kontrolą, zachowaj kontrast i wolne pole oraz sprawdź wydruk z oczekiwanej odległości.'],
        ['Etykiety regulowane lub wymagane umową', 'Zastosuj właściwą specyfikację branżową, prawną i odbiorcy. Narzędzie graficzne nie zastępuje formalnej weryfikacji ani zatwierdzenia.'],
      ],
      examples: [
        ['Wewnętrzny kod półki', 'MAG-A-04-017', 'Code 128 może zapisać lokalizację, jeśli system magazynowy kontroluje przydzielanie wartości.'],
        ['Detaliczny EAN-13', '5901234123457', 'Narzędzie sprawdza i renderuje, ale rejestr GS1 i zasady odbiorcy określają, czy GTIN należy do firmy.'],
        ['Zadanie seryjne', 'produkty.csv → PDF', 'Generator raportuje błędne wiersze i tworzy arkusz lokalnie bez przesyłania listy produktów.'],
      ],
      mistakes: [
        'Zakładanie, że utworzony obraz oznacza własność numeru. Symbol i identyfikator to dwie różne kwestie.',
        'Brak ochrony przed duplikatami kodów wewnętrznych. Poprawna wartość Code 128 może wskazać zły towar, gdy numer zostanie użyty ponownie.',
        'Publikowanie etykiet bez kontroli skali, pól ochronnych, kontrastu, kalibracji drukarki i materiału.',
        'Traktowanie odczytu telefonem jako dowodu zgodności ze specyfikacją odbiorcy albo wymaganiem formalnej weryfikacji.',
      ],
      faq: [
        ['Czy mogę komercyjnie używać pobranych plików PNG, SVG i PDF?', 'Tak. Narzędzie nie pobiera opłaty za generowanie grafiki. Firma nadal odpowiada za dane, prawa do identyfikatora, wymagania odbiorców i końcowy wydruk.'],
        ['Czy darmowy generator EAN-13 nadaje numer produktu?', 'Nie. Może obliczyć cyfrę i utworzyć EAN-13, lecz globalnie unikalne detaliczne GTIN są przydzielane przez organizacje członkowskie GS1.'],
        ['Czy potrzebuję konta?', 'Nie do pojedynczego generowania, dekodowania i ograniczonego eksportu paczek. Konto dodaje zapisane kody, szablony, profile drukarek i historię.'],
        ['Czy dane produktów są przesyłane podczas eksportu paczki?', 'Parser CSV i generowanie działają w przeglądarce. Funkcje konta wysyłają wyłącznie rekordy świadomie zapisane przez użytkownika.'],
      ],
      links: [['Generator pojedynczego kodu', '/pl/'], ['Generator paczek CSV', '/pl/generator-kodow-z-csv'], ['Dekoder kodów', '/pl/decoder'], ['Poradnik GTIN, EAN i UPC', '/pl/poradniki/gtin-ean-upc'], ['EAN-13 dla żywności', '/pl/poradniki/kod-ean-13-produkt-spozywczy']],
      sources: [['GS1: uzyskanie kodu i GTIN', gs1Sources.get], ['GS1: weryfikacja GTIN', gs1Sources.verify], ['Regulamin Generatora', 'https://barcode-generator.daytodayapps.com/pl/regulamin']],
    },
  },
];
